Module7 task1
htmlacademy-javascript/1248355-keksobooking-27 pull request #5
Opened 2022-10-11 09:08 UTC by AndreyOtin

2022-10-11 11:25 UTC, ArtMan-8 requested changes

2022-10-11 11:25 UTC, ArtMan-8 commented on js/util.js
> +const hideElement = (element) => element.classList.add('hidden');
А обратная операция пока не нужна?

2022-10-11 11:25 UTC, ArtMan-8 commented on js/mock-data.js
> +const createDataFillerFn = (photoData) => (_, index) => {
Зачем постфикс`Fn`?

2022-10-11 11:25 UTC, ArtMan-8 commented on js/main.js
> +import './render-advertisements.js';
Не нужно не явно, что-то делать.
Импортирую функцию рендера и запускай её.

2022-10-11 11:25 UTC, ArtMan-8 commented on js/render-advertisements.js
> +const QuerySelectors = {
Используется как словарь, множественное число не нужно
```suggestion
const QuerySelector = {
```

2022-10-11 11:25 UTC, ArtMan-8 commented on js/render-advertisements.js
> +const typesMap = {
Название не отображает назначение этого словаря. Как-то иначе попробуй назвать.

2022-10-11 11:25 UTC, ArtMan-8 commented on js/render-advertisements.js
> +      data.offer.photos.forEach((photo, index) => {
Блоки генерации попробуй вынести в отдельные функции. Этот и ниже.

2022-10-11 12:28 UTC, AndreyOtin commented on js/render-advertisements.js
> +const typesMap = {
nameByType?

2022-10-11 12:34 UTC, AndreyOtin commented on js/mock-data.js
> +const createDataFillerFn = (photoData) => (_, index) => {
Переименовал модуль на mock-data вместо generate-advertisments так как понял выполняя эту домашку что это название скорее всего подходит для данного модуля. Решил также изменить название fn, так как скорее мы создаем информацию, чем обьявления. Так не стоит делать? Вернуть назад?

2022-10-11 12:36 UTC, AndreyOtin commented on js/util.js
> +const hideElement = (element) => element.classList.add('hidden');
const toggleElement = (element) => element.classList.toggle('hidden'); ?

2022-10-11 12:51 UTC, AndreyOtin commented on js/mock-data.js
> +const createDataFillerFn = (photoData) => (_, index) => {
Так же вчера на лекции сказали, что не использующиеся аргументы нужно убирать в _. И в результирующую функцию generateData также добавил параметр числа обьектов с данными так как оказывается для задания нужно отрисовать пока njkmrj одно обьявление. Все это выяснилось только сейчас)

2022-10-11 16:06 UTC, ArtMan-8 commented on js/render-advertisements.js
> +const typesMap = {
`typeToRus`

2022-10-11 16:16 UTC, ArtMan-8 commented on js/render-advertisements.js
> +  adData.forEach((data) => {
И попробуй это тоже вынести в функцию

2022-10-12 05:52 UTC, ArtMan-8 approved these changes

2022-10-12 05:52 UTC, merged